[files]
ignore-files = true

[default.extend-words]
Nam = "Nam"

[default]
extend-ignore-re = [
  "\\.ist"
]

[type.pdf]
extend-glob = ["*.pdf"]
check-file = false

[type.png]
extend-glob = ["*.png"]
check-file = false


[type.blg]
extend-glob = ["*.blg"]
check-file = false

[type.log]
extend-glob = ["*.log"]
check-file = false
